apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: onnx-model-1724422391134-vs # .replace() with python logic
spec:
  hosts:
  - "*"  
  gateways:
  - kserve-gateway
  http:
  - match:
    - uri:
        prefix: /v1/models/onnx-model-1724422391134 # .replace() with python logic
    route:
    - destination:
        host: onnx-model-1724422391134.onnx-model-1724422391134.svc.cluster.local # .replace() with python logic
        port:
          number: 80