name: Install Knative Serving, Istio, Cert-Manager, and KServe

'on':
  repository_dispatch:
    types:
      - deploy-kserve

jobs:
  install-knative-serving-istio-certmanager-kserve:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.MODEL_DEPLOYMENT_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.MODEL_DEPLOYMENT_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # to replace in python logic

      - name: Install the latest stable version of kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region us-east-1 --name mlops-lite-cluster # to replace in python logic

      - name: Install Cosign
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: "v2.0.2"

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Install istioctl
        run: curl -L https://istio.io/downloadIstio | ISTIO_VERSION=1.14.1 sh - && sudo mv istio-1.14.1/bin/istioctl /usr/local/bin/

      - name: Verify Knative Serving images
        run: |
          curl -sSL https://github.com/knative/serving/releases/download/knative-v1.14.1/serving-core.yaml \
            | grep 'gcr.io/' | awk '{print $2}' | sort | uniq \
            | xargs -n 1 \
              cosign verify -o text \
                --certificate-identity=signer@knative-releases.iam.gserviceaccount.com \
                --certificate-oidc-issuer=https://accounts.google.com

      - name: Install Knative Serving CRDs
        run: |
          kubectl apply -f https://github.com/knative/serving/releases/download/knative-v1.14.1/serving-crds.yaml

      - name: Install Knative Serving core components
        run: |
          kubectl apply -f https://github.com/knative/serving/releases/download/knative-v1.14.1/serving-core.yaml

      - name: Install Kourier
        run: |
          kubectl apply -f https://github.com/knative/net-kourier/releases/download/knative-v1.14.0/kourier.yaml
          kubectl patch configmap/config-network \
            --namespace knative-serving \
            --type merge \
            --patch '{"data":{"ingress-class":"kourier.ingress.networking.knative.dev"}}'

      - name: Verify Knative Serving installation
        run: |
          kubectl get pods -n knative-serving

      - name: Fetch Kourier External IP
        run: |
          kubectl --namespace kourier-system get service kourier

      - name: Install Istio
        run: |
          istioctl install -y

      - name: Install Knative Istio controller
        run: |
          kubectl apply -f https://github.com/knative/net-istio/releases/download/knative-v1.14.1/net-istio.yaml

      - name: Enable sidecar injection on knative-serving namespace
        run: |
          kubectl label namespace knative-serving istio-injection=enabled

      - name: Apply PeerAuthentication for mTLS
        run: |
          cat <<EOF | kubectl apply -f -
          apiVersion: "security.istio.io/v1beta1"
          kind: "PeerAuthentication"
          metadata:
            name: "default"
            namespace: "knative-serving"
          spec:
            mtls:
              mode: PERMISSIVE
          EOF

      - name: Verify Istio installation
        run: |
          istioctl verify-install

      - name: Install cert-manager
        run: |
          kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.15.1/cert-manager.yaml

      - name: Install KServe
        run: |
          kubectl apply -f https://github.com/kserve/kserve/releases/download/v0.13.0/kserve.yaml

      - name: Install KServe Built-in ClusterServingRuntimes
        run: |
          kubectl apply -f https://github.com/kserve/kserve/releases/download/v0.13.0/kserve-cluster-serving-runtime.yaml
