apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kserve-controller-manager-role
rules:
- apiGroups: ["serving.kserve.io"]
  resources: ["inferencegraphs", "clusterstoragecontainers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]