apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server
  namespace: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-server
  template:
    metadata:
      labels:
        app: mlflow-server
    spec:
      containers:
      - name: mlflow-server
        image: public.ecr.aws/c3s1g1e1/mlops-lite:latest # Custom mlflow image with Postgres support (using x86-64 architecture for cloud deployment)
        imagePullPolicy: Always # Always pull the latest image even if no yaml changes
        ports:
        - containerPort: 5000
        env:
        - name: POSTGRES_USERNAME
          valueFrom:
            configMapKeyRef:
              name: mlflow-config
              key: POSTGRES_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: mlflow-config
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: mlflow-config
              key: POSTGRES_HOST
        - name: POSTGRES_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mlflow-config
              key: POSTGRES_DATABASE
        - name: S3_BUCKET
          valueFrom:
            configMapKeyRef:
              name: mlflow-config
              key: S3_BUCKET
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: mlflow-config
              key: AWS_REGION
        command: ["mlflow", "server"]  # Explicitly set the command to run the mlflow server
        args:
        - --backend-store-uri=postgresql://$(POSTGRES_USERNAME):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST)/$(POSTGRES_DATABASE)
        - --default-artifact-root=$(S3_BUCKET)
        - --host=0.0.0.0