apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server
  namespace: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-server
  template:
    metadata:
      labels:
        app: mlflow-server
    spec:
      containers:
      - name: mlflow-server
        image: ghcr.io/mlflow/mlflow:latest
        command: ["mlflow", "server"]
        ports:
        - containerPort: 5000
        env:
        - name: MLFLOW_TRACKING_URI
          valueFrom:
            configMapKeyRef:
              name: mlflow-config
              key: POSTGRES_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: mlflow-config
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: mlflow-config
              key: POSTGRES_HOST
        - name: POSTGRES_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mlflow-config
              key: POSTGRES_DATABASE
        - name: ARTIFACT_URI
          valueFrom:
            configMapKeyRef:
              name: mlflow-config
              key: S3_BUCKET
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: mlflow-config
              key: AWS_REGION
        args:
        - --backend-store-uri=postgresql://$(POSTGRES_USERNAME):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST)/$(POSTGRES_DATABASE)
        - --default-artifact-root=$(S3_BUCKET)