apiVersion: v1
kind: ConfigMap
metadata:
  name: mlflow-config
  namespace: mlflow
data:
  DB_USERNAME: admin
  DB_PASSWORD: Zcfx1zWBLLZGmP7wP4Ws
  DB_HOST: mlflow-mysql-v2.clkyuqewyewf.us-east-1.rds.amazonaws.com
  DB_DATABASE: mlflowdb
  S3_BUCKET: s3://mlflow-lite-bucket
  AWS_REGION: us-east-1

