apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: "onnx-model-1724529354426"
  namespace: "onnx-model-1724529354426"
spec:
  predictor:
    model:
      modelFormat:
        name: onnx
      protocolVersion: v2
      storageUri: "s3://mlflow-lite-bucket/mlflow-artifacts/9/b22cbe1139b347cf8c62906119c8a6a6/artifacts/model"
      #resources:
        #requests:
         #cpu: "500m"
         #memory: "1Gi"
         #limits:
          #cpu: "1"
          #memory: "2Gi"