apiVersion: serving.kserve.io/v1beta1
kind: "InferenceService"
metadata:
  name: "onnx-model-1724774116882"
  namespace: "onnx-model-1724774116882"
spec:
  predictor:
    model:
      modelFormat:
        name: "onnx"
      storageUri: "s3://mlflow-lite-bucket/mlflow-artifacts/25/45b7cc70c3ab4ce98f052949f2bc6174/artifacts/model"
      runtime: kserve-tritonserver
      #protocolVersion: v2
      #resources:
        #requests:
         #cpu: "500m"
         #memory: "1Gi"
         #limits:
          #cpu: "1"
          #memory: "2Gi"

