apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: "onnx-model-1724422391134"
  namespace: "onnx-model-1724422391134"
spec:
  predictor:
    model:
      modelFormat:
        name: onnx
      protocolVersion: v2
      storageUri: "s3://mlflow-lite-bucket/mlflow-artifacts/8/6881e22a9ca3465e93a14854c07995bb/artifacts/model"
      resources:
        requests:
          cpu: "500m"
          memory: "1Gi"
        limits:
          cpu: "1"
          memory: "2Gi"