apiVersion: serving.kserve.io/v1beta1
kind: "InferenceService"
metadata:
  name: "onnx-model-1725202546360"
  namespace: "onnx-model-1725202546360"
spec:
  predictor:
    onnx: #Todo make abstract and inject based on model manager
      storageUri: "s3://mlflow-lite-bucket/mlflow-artifacts/31/28ad763c3bd84e2a80fb8ebfef57195b/artifacts/model"
    minReplicas: 1
    maxReplicas: 1

