apiVersion: serving.kserve.io/v1beta1
kind: "InferenceService"
metadata:
  name: "onnx-model-1724769816507"
  namespace: "onnx-model-1724769816507"
spec:
  predictor:
    model:
      modelFormat:
        name: "onnx"
      storageUri: "s3://mlflow-lite-bucket/mlflow-artifacts/10/f30f7ac6758b45d2a1c6577d1424e492/artifacts/model"
      runtime: kserve-tritonserver
      #protocolVersion: v2
      #resources:
        #requests:
         #cpu: "500m"
         #memory: "1Gi"
         #limits:
          #cpu: "1"
          #memory: "2Gi"

